# Generated by Django 4.2.11 on 2024-05-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('category', models.CharField(choices=[('App', 'App'), ('Card', 'Card'), ('Web', 'Web')], max_length=10)),
            ],
        ),
    ]
