# Generated by Django 4.2.11 on 2024-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=0, help_text='Max 100'),
        ),
    ]
